{{- if and .Values.networkPolicy.enabled .Values.hugeGraph.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-query-api-to-hugegraph
  namespace: {{ .Values.namespace.observability }}
spec:
  podSelector:
    matchLabels:
      app: hugegraph
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: query-api
        - podSelector:
            matchLabels:
              app: graph-schema-migrator
      ports:
        - protocol: TCP
          port: 8080
{{- end }}
