import React from 'react'
import { Card, Col, Row, Tag, Typography } from 'antd'
import type { InvestigationViewModel } from '../../features/investigation/model'
import GraphContextPanel from '../../components/graph/GraphContextPanel'

export const ImpactPane: React.FC<{ model: InvestigationViewModel; graphContext: Record<string, unknown> | null }> = ({ model, graphContext }) => <Card title="影响面" size="small"><Typography.Text strong>{model.scope.resourceId || '未提供资源'}</Typography.Text><Typography.Paragraph type="secondary" style={{ margin: '8px 0' }}>{model.intent || '未提供调查目标'}</Typography.Paragraph><GraphContextPanel context={graphContext} /><div style={{ marginTop: 12 }}><Tag>状态：{model.status}</Tag><Tag>证据：{model.evidence.length} 条</Tag></div></Card>

export const EvidenceTimeline: React.FC<{ model: InvestigationViewModel; tools: Array<{ tool_name: string; status: string; result_quality?: string; eligible_for_evidence?: boolean }>; onEvidenceClick?: (id: string) => void }> = ({ model, tools, onEvidenceClick }) => <Card title="证据时间线" size="small"><div className="evidence-timeline">{model.evidence.length ? model.evidence.map((e) => <div className="evidence-timeline__item" key={e.id} onClick={() => onEvidenceClick?.(e.id)} onKeyDown={(event) => { if (onEvidenceClick && (event.key === 'Enter' || event.key === ' ')) { event.preventDefault(); onEvidenceClick(e.id) } }} role={onEvidenceClick ? 'button' : undefined} tabIndex={onEvidenceClick ? 0 : undefined}><div><Tag>{e.source}</Tag><Tag color={e.reliability != null && e.reliability >= 0.8 ? 'green' : 'blue'}>{e.reliability == null ? '未提供' : e.reliability}</Tag></div><Typography.Text>{e.fact || '证据内容未提供'}</Typography.Text></div>) : <Typography.Text type="secondary">暂无持久化证据</Typography.Text>}</div>{tools.length > 0 && <div style={{ marginTop: 16 }}><Typography.Text strong>工具活动</Typography.Text>{tools.map((tool, index) => <div key={`${tool.tool_name}-${index}`} style={{ marginTop: 6, fontSize: 12 }}><Tag>{tool.tool_name}</Tag><Tag>{tool.status}</Tag><Typography.Text type="secondary">{tool.result_quality || '质量未提供'} · {tool.eligible_for_evidence ? '可作为证据' : '不可作为证据'}</Typography.Text></div>)}</div>}</Card>

export const JudgementPane: React.FC<{ model: InvestigationViewModel; onOpenAction?: () => void }> = ({ model, onOpenAction }) => <Card title="AI 判断与下一步" size="small"><Typography.Title level={5} style={{ marginTop: 0 }}>{model.conclusion.title || '根因未知'}</Typography.Title><Typography.Text type="secondary">置信度：{model.conclusion.confidence == null ? '未提供' : `${Math.round(model.conclusion.confidence * 100)}%`}</Typography.Text>{model.conclusion.state === 'insufficient_evidence' && <div className="insufficient-evidence" role="alert">证据不足：当前结论不能作为执行依据。</div>}<div style={{ marginTop: 16 }}>{model.hypotheses.length ? model.hypotheses.map((h) => <div key={h.id} style={{ marginBottom: 12 }}><Typography.Text strong>{h.claim}</Typography.Text><div><Tag color={h.confidence >= 0.8 ? 'green' : 'blue'}>{Math.round(h.confidence * 100)}%</Tag>{h.contradicts.map((item) => <Tag color="red" key={`c-${item}`}>矛盾：{item}</Tag>)}{h.missing.map((item) => <Tag color="orange" key={`m-${item}`}>缺失：{item}</Tag>)}</div></div>) : <Typography.Text type="secondary">暂无持久化假设</Typography.Text>}</div>{model.action && <div style={{ marginTop: 12, borderTop: '1px solid var(--border-soft)', paddingTop: 12 }}><Typography.Text strong>处置动作</Typography.Text><div><Tag>{model.action.status}</Tag><Tag color="gold">风险：{model.action.risk || '未提供'}</Tag></div>{onOpenAction && <button type="button" className="link-button" onClick={onOpenAction}>打开动作中心</button>}</div>}</Card>

const InvestigationShell: React.FC<{ model: InvestigationViewModel; graphContext: Record<string, unknown> | null; tools: Array<{ tool_name: string; status: string; result_quality?: string; eligible_for_evidence?: boolean }>; onOpenAction?: () => void; onEvidenceClick?: (id: string) => void }> = ({ model, graphContext, tools, onOpenAction, onEvidenceClick }) => <Row gutter={[16, 16]} className="investigation-grid"><Col xs={24} lg={8}><ImpactPane model={model} graphContext={graphContext} /></Col><Col xs={24} lg={8}><EvidenceTimeline model={model} tools={tools} onEvidenceClick={onEvidenceClick} /></Col><Col xs={24} lg={8}><JudgementPane model={model} onOpenAction={onOpenAction} /></Col></Row>

export default InvestigationShell
