package k8sboundary

import (
	"errors"
	"strings"
	"testing"

	"github.com/observability-platform/ai-apm-query-go/internal/store"
)

type fakeRegistrationStore struct {
	clusters  map[string]*store.Cluster // by ClusterID
	byUID     map[string]*store.Cluster // by KubernetesIdentityUID
	registerErr error
}

func (f *fakeRegistrationStore) RegisterCluster(c *store.Cluster) error {
	if f.registerErr != nil {
		return f.registerErr
	}
	// Mirror the production duplicate-active guard.
	if existing, ok := f.byUID[c.KubernetesIdentityUID]; ok && existing.ClusterID != c.ClusterID {
		return store.ErrClusterIdentityDuplicate
	}
	f.clusters[c.ClusterID] = c
	f.byUID[c.KubernetesIdentityUID] = c
	return nil
}

func (f *fakeRegistrationStore) FindActiveByKubeSystemUID(uid string) (*store.Cluster, error) {
	c, ok := f.byUID[uid]
	if !ok {
		return nil, nil
	}
	return c, nil
}

func TestClusterRegistrarDiscoversIdentityFromTargetCluster(t *testing.T) {
	kcreader := &fakeKubeconfigReader{kcByRef: map[string]string{secretA: kcA}}
	ireader := &fakeIdentityReader{uidByKubeconfig: map[string]string{kcA: uidA}}
	dao := &fakeRegistrationStore{clusters: map[string]*store.Cluster{}, byUID: map[string]*store.Cluster{}}

	r := NewClusterRegistrar(kcreader, ireader, dao)
	got, err := r.Register(ClusterRegistration{
		TenantID:      "33333333-3333-4333-8333-333333333333",
		Slug:          "orbstack",
		Name:          "Orbstack",
		Environment:   "prod",
		Region:        "cn-shanghai",
		CredentialRef: secretA,
	})
	if err != nil {
		t.Fatalf("Register() error = %v", err)
	}
	// The persisted identity MUST be the one discovered from the target cluster,
	// NOT anything a caller could have supplied (ClusterRegistration has no UID).
	if got.KubernetesIdentityUID != uidA {
		t.Fatalf("persisted identity = %q, want discovered uidA %q", got.KubernetesIdentityUID, uidA)
	}
	if !canonicalUUID.MatchString(got.ClusterID) {
		t.Fatalf("generated cluster_id = %q is not canonical", got.ClusterID)
	}
	if got.KubernetesIdentityUID == got.ClusterID {
		t.Fatalf("cluster_id must never equal kube-system UID")
	}
	// The canonical UUID was generated by the registrar, not derived from the UID.
	if got.ClusterID == uidA {
		t.Fatalf("cluster_id must be independently generated")
	}
}

func TestClusterRegistrarRejectsWhenCredentialUnresolvable(t *testing.T) {
	kcreader := &fakeKubeconfigReader{kcByRef: map[string]string{}, errByRef: map[string]error{secretA: errSecretNotFound}}
	ireader := &fakeIdentityReader{}
	dao := &fakeRegistrationStore{clusters: map[string]*store.Cluster{}, byUID: map[string]*store.Cluster{}}

	r := NewClusterRegistrar(kcreader, ireader, dao)
	_, err := r.Register(ClusterRegistration{TenantID: "33333333-3333-4333-8333-333333333333", CredentialRef: secretA})
	if err == nil {
		t.Fatal("Register(unresolvable credential) error = nil, want fail")
	}
	if len(dao.clusters) != 0 {
		t.Fatalf("Register(unresolvable credential) wrote %d rows, want 0 (no partial registration)", len(dao.clusters))
	}
}

func TestClusterRegistrarRejectsWhenIdentityProbeFails(t *testing.T) {
	kcreader := &fakeKubeconfigReader{kcByRef: map[string]string{secretA: kcA}}
	ireader := &fakeIdentityReader{uidByKubeconfig: map[string]string{}}
	dao := &fakeRegistrationStore{clusters: map[string]*store.Cluster{}, byUID: map[string]*store.Cluster{}}

	r := NewClusterRegistrar(kcreader, ireader, dao)
	_, err := r.Register(ClusterRegistration{TenantID: "33333333-3333-4333-8333-333333333333", CredentialRef: secretA})
	if err == nil {
		t.Fatal("Register(identity probe fails) error = nil, want fail")
	}
	if len(dao.clusters) != 0 {
		t.Fatalf("Register(identity probe fails) wrote %d rows, want 0", len(dao.clusters))
	}
}

func TestClusterRegistrarRejectsDuplicateActivePhysicalCluster(t *testing.T) {
	kcreader := &fakeKubeconfigReader{kcByRef: map[string]string{secretA: kcA, secretB: kcB}}
	ireader := &fakeIdentityReader{uidByKubeconfig: map[string]string{kcA: uidA, kcB: uidB}}
	dao := &fakeRegistrationStore{
		clusters: map[string]*store.Cluster{},
		byUID: map[string]*store.Cluster{
			uidA: {ClusterID: uuidA, KubernetesIdentityUID: uidA},
		},
	}

	r := NewClusterRegistrar(kcreader, ireader, dao)

	// A credential resolving to uidA while uidA is already active must be rejected:
	// the same physical Kubernetes cluster cannot be active under two canonical UUIDs.
	kcA2 := "kubeconfig-A2"
	ireader.uidByKubeconfig[kcA2] = uidA
	kcreader.kcByRef["k8s-secret://aiops/cluster-a2"] = kcA2
	_, err := r.Register(ClusterRegistration{TenantID: "33333333-3333-4333-8333-333333333333", Slug: "orbstack-dup", CredentialRef: "k8s-secret://aiops/cluster-a2"})
	if !errors.Is(err, store.ErrClusterIdentityDuplicate) {
		t.Fatalf("Register(duplicate active physical cluster) error = %v, want ErrClusterIdentityDuplicate", err)
	}
}

func TestNewCanonicalUUIDIsCanonicalAndLowercase(t *testing.T) {
	for i := 0; i < 50; i++ {
		id, err := newCanonicalUUID()
		if err != nil {
			t.Fatalf("newCanonicalUUID() error = %v", err)
		}
		if !canonicalUUID.MatchString(id) {
			t.Fatalf("newCanonicalUUID() = %q does not match canonical pattern", id)
		}
		if strings.ToLower(id) != id {
			t.Fatalf("newCanonicalUUID() = %q is not lowercase", id)
		}
	}
}
