"""Versioned graph contract metadata."""
GRAPH_SCHEMA_VERSION = "graph-schema-v2"
GRAPH_DTO_VERSION = "graph-dto-v1"
GRAPH_UI_VERSION = "graph-ui-v1"
PROPAGATION_VERSION = "propagation-v1"
RCA_SCORE_VERSION = "rca-score-v1"

ENTITY_VERTEX_LABEL = "Entity"
ENTITY_ID_MODE = "CUSTOMIZE_STRING"
EDGE_FREQUENCY = "SINGLE"

__all__ = ["GRAPH_SCHEMA_VERSION", "GRAPH_DTO_VERSION", "GRAPH_UI_VERSION", "PROPAGATION_VERSION",
           "RCA_SCORE_VERSION", "ENTITY_VERTEX_LABEL", "ENTITY_ID_MODE", "EDGE_FREQUENCY"]
