#!/usr/bin/env python3
"""P1-SUP1: generate the hashed production lock from a multi-platform wheelhouse.

Input : ai-orchestrator/wheelhouse/{amd64,arm64}/*.whl (generated by
        deploy/scripts/build-wheelhouse.sh from requirements.txt)
Output: ai-orchestrator/requirements-lock.txt  (pkg==ver --hash=sha256:...)
        ai-orchestrator/wheelhouse.sha256      (per-file sha256 for sha256sum -c)
Runs in the Dockerfile as:
    COPY requirements-lock.txt wheelhouse.sha256 wheelhouse/ wheelhouse/
    sha256sum -c wheelhouse.sha256
    pip install --no-index --find-links=wheelhouse --require-hashes \
        -r requirements-lock.txt

pip's --require-hashes accepts a package line with MULTIPLE --hash= entries and
will install whichever hash matches the wheel actually available in the
find-links set, so both platform wheels of a package are listed on one line.
"""
import hashlib
import pathlib
import sys
from packaging.utils import parse_wheel_filename

repo_root = pathlib.Path(__file__).resolve().parents[2]
orchestrator = repo_root / "ai-orchestrator"
wheelhouse = orchestrator / "wheelhouse"

platform_dirs = ["amd64", "arm64"]
by_pkg: dict[str, dict[str, list[str]]] = {}  # pkg -> ver -> [sha256]

files = {}
for plat in platform_dirs:
    d = wheelhouse / plat
    if not d.is_dir():
        print(f"missing wheelhouse platform dir: {d}", file=sys.stderr)
        sys.exit(1)
    for whl in sorted(d.glob("*.whl")):
        name, ver, *_ = parse_wheel_filename(whl.name)
        norm = name.replace("-", "_")
        digest = hashlib.sha256(whl.read_bytes()).hexdigest()
        by_pkg.setdefault(norm, {}).setdefault(ver, []).append(digest)
        files[whl] = digest

if not by_pkg:
    print("no wheels found", file=sys.stderr)
    sys.exit(1)

lines = []
for pkg in sorted(by_pkg):
    for ver in sorted(by_pkg[pkg]):
        hashes = " ".join(f"--hash=sha256:{h}" for h in sorted(by_pkg[pkg][ver]))
        lines.append(f"{pkg}=={ver} {hashes}")
lock = orchestrator / "requirements-lock.txt"
lock.write_text("\n".join(lines) + "\n", encoding="utf-8")

sha = orchestrator / "wheelhouse.sha256"
with sha.open("w", encoding="utf-8") as fh:
    for whl in sorted(files):
        fh.write(f"{files[whl]}  {whl.relative_to(wheelhouse)}\n")

print(f"lock: {len(lines)} packages -> {lock.relative_to(repo_root)}")
print(f"sha : {len(files)} files   -> {sha.relative_to(repo_root)}")
