import React, { useMemo, useState } from 'react'
import type { GraphRelationRow } from './graphPresentation'

export default function GraphRelationList({ rows, onLocate, totalEdges, aggregated = false }: { rows: GraphRelationRow[]; onLocate?: (edgeId: string) => void; totalEdges?: number; aggregated?: boolean }) {
  const [descending, setDescending] = useState(false)
  const [equivalentOpen, setEquivalentOpen] = useState(false)
  const sorted = useMemo(() => [...rows].sort((left, right) => `${left.sourceName}${left.label}${left.targetName}`.localeCompare(`${right.sourceName}${right.label}${right.targetName}`) * (descending ? -1 : 1)), [descending, rows])
  return <section className="graph-relation-list" aria-label="关系明细"><div className="section-heading"><strong>关系明细</strong><span>{aggregated && totalEdges ? `当前 ${rows.length} / 总计 ${totalEdges}` : `${rows.length} 条`}</span><button type="button" onClick={() => setDescending((value) => !value)}>{descending ? '恢复顺序' : '按名称排序'}</button><button type="button" aria-label="等价关系列表" onClick={() => setEquivalentOpen((value) => !value)}>{equivalentOpen ? '收起等价关系列表' : '等价关系列表'}</button></div>{equivalentOpen && <div className="graph-relation-list__equivalent" role="region" aria-label="等价关系列表">{sorted.length ? sorted.map((row) => <div className="graph-relation-list__equivalent-row" key={`equivalent:${row.id}`}><span>{row.sourceName}</span><strong>{row.label}</strong><span>→</span><span>{row.targetName}</span><small>{row.factStatus === 'fact' ? '事实' : '推断'} · {row.sourceRef}{row.syncedAt ? ` · ${row.syncedAt}` : ''}</small></div>) : <div className="graph-relation-list__empty">暂无关系</div>}</div>}{sorted.length ? sorted.map((row) => <button type="button" key={row.id} className="graph-relation-list__row" aria-label={`${row.sourceName} ${row.label} ${row.targetName}`} onClick={() => onLocate?.(row.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onLocate?.(row.id) } }}><span>{row.sourceName}</span><em>{row.label}</em><span>→ {row.targetName}</span></button>) : <div className="graph-relation-list__empty">暂无关系</div>}</section>
}
