from __future__ import annotations
from collections import defaultdict
from typing import Any, Iterable

EVIDENCE_CATEGORIES = {"metric", "trace", "log", "alert", "change", "kubernetes_event", "kubevirt_event",
                       "hardware_sensor", "hardware_sel", "inventory", "graph_relation"}


def normalize_evidence(items: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    result = []
    for item in items:
        if not isinstance(item, dict):
            continue
        category = str(item.get("category") or item.get("evidence_type") or "").strip().lower()
        if category in {"metric_anomaly", "capacity_anomaly"}: category = "metric"
        if category in {"trace_anomaly"}: category = "trace"
        if category in {"log_error", "log_pattern"}: category = "log"
        if category in {"k8s_state", "k8s_event"}: category = "kubernetes_event"
        if category == "hardware_event": category = "hardware_sensor"
        copy = dict(item); copy["category"] = category
        result.append(copy)
    return result


def evidence_for_candidate(items: Iterable[dict[str, Any]], entity_uid: str) -> list[dict[str, Any]]:
    """Return only evidence explicitly bound to the candidate entity.

    Unbound evidence remains useful context for an investigation, but allowing
    it into every candidate's score makes a single global metric look like
    corroboration for unrelated resources.  The canonical RCA contract
    requires an ``entity_uid`` before evidence can affect a candidate score.
    """
    candidate_uid = str(entity_uid or "")
    if not candidate_uid:
        return []
    return [item for item in normalize_evidence(items)
            if str(item.get("entity_uid") or "") == candidate_uid]


def independent_categories(items: Iterable[dict[str, Any]]) -> int:
    """Count independent provenance groups, with category fallback.

    Multiple projections (for example an alert and a metric) generated by the
    same query/source are one observation, not independent corroboration.
    Older providers do not emit a correlation group, so their category is used
    as a deterministic compatibility key until they migrate to the V2
    envelope.
    """
    groups: set[str] = set()
    for item in normalize_evidence(items):
        if item.get("category") not in EVIDENCE_CATEGORIES:
            continue
        group = str(item.get("correlation_group") or "").strip()
        groups.add(group if group else f"category:{item.get('category')}")
    return len(groups)


def unbound_context(items: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return evidence that cannot be attributed to a candidate entity."""
    return [item for item in normalize_evidence(items) if not str(item.get("entity_uid") or "").strip()]


def group_by_entity(items: Iterable[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    grouped = defaultdict(list)
    for item in normalize_evidence(items):
        grouped[str(item.get("entity_uid") or "")].append(item)
    return dict(grouped)
